version: "2.1"
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - WEBUI_PORT=8080
    volumes:
      # - /path/to/appdata/config:/config
      - /home/trident/Downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  ngrok:
    container_name: ngrok
    image: wernight/ngrok:latest
    env_file:
      - ngrok.env
    ports:
      - 4551:4551
    links:
      - client

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - "./downloads:/media"

    ports:
      - 5000:5000

    command: uvicorn server.server:app --host 0.0.0.0 --port 5000

  client:
    build:
      context: .
      dockerfile: client/Dockerfile

    ports:
      - 5001:5001

    command: uvicorn client.client:app --host 0.0.0.0 --port 5001
